spring.application.name=assignment01

# ===============================
# DATABASE CONNECTION
# ===============================

spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=SBA302_Assignment1;encrypt=true;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=1231

# ===============================
# JPA / HIBERNATE
# ===============================
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


# SERVLET SESSIOn
server.servlet.session.cookie.same-site=lax
server.servlet.session.cookie.secure=false
server.servlet.session.timeout=30m

